name: Build ESP32 Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build with ESP-IDF
      uses: addnab/docker-run-action@v3
      with:
        image: espressif/idf:release-v5.2
        options: -v ${{ github.workspace }}/firmware:/project -w /project
        run: |
          idf.py set-target esp32s3
          idf.py build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp32s3-firmware
        path: firmware/build/*.bin
        retention-days: 1
